### ISSUE TITLE
Ionic 3 - ios platform not working

### ISSUE THREAD

**Issue by luciandarabus** [OneSignal/OneSignal-Cordova-SDK#196]
I am trying to use oneSignal with ionic 3.3.0 and access the onesignal plugin via https://ionicframework.com/docs/native/onesignal/
but it doesn't work on ios and I get the following error:

[09:44:01]  console.warn: Native: tried calling OneSignal.startInit, but the OneSignal plugin is not installed. 
[09:44:01]  console.warn: Install the OneSignal plugin: 'ionic plugin add onesignal-cordova-plugin' 
[09:44:01]  console.warn: Native: tried calling OneSignal.inFocusDisplaying, but the OneSignal plugin is not installed. 
[09:44:01]  console.warn: Install the OneSignal plugin: 'ionic plugin add onesignal-cordova-plugin' 
[09:44:01]  console.warn: Native: tried calling OneSignal.handleNotificationReceived, but the OneSignal plugin is not 
            installed. 
[09:44:01]  console.warn: Install the OneSignal plugin: 'ionic plugin add onesignal-cordova-plugin' 

I've also tried to access the plugin via windows.plugins.OneSignal  and again it doesn't work and it led me to the conclusion that the problem is with the plugin.

Both examples work on android. 

There is also an issue open in the ionic forum:

https://forum.ionicframework.com/t/in-ionic-2-tried-calling-onesignal-startinit-but-the-onesignal-plugin-is-not-installed/91967

and in the git repository of the component

https://github.com/ionic-team/ionic-native/issues/1674

Can you help fixing the problem?

Update: I've tried downgrading the plugin version and went down all versions till 2.0.8 and I get the same error.

**Comment by jkasten2** [comment]
@luciandarabus Are you able to reproduce the issue with a new Ionic project as well? Did you get any warnings when running `ionic plugin add onesignal-cordova-plugin`? Can you check that your project directory contains `plugins/onesignal-cordova-plugin/www/OneSignal.js`?

**Comment by jeffscm** [comment]
using ionic 3.4.0

when you use ionic plugin add onesignal-cordova-plugin
it will ask to update pods (if not already done)
ionic platform rm ios
rm -rf plugins/
ionic platform add iOS
npm install --save @ionic-native/onesignal
ionic build ios

xcode part: 

open Pods folder
drag Pods/OneSignal/../../../OneSignal.framework to the Build Phases -> Link binaries with libraries
on the Build Phases -> Link binaries with libraries remove all Pods references
build the project
done!

is it a bug? a problem? missing some link?
I will need to automate all this for the moment.

**Comment by jkasten2** [comment]
@jeffscm Thanks for the details. The Xcode steps shouldn't be required to build. It's only needed to use Notification Action Buttons and Media Attachments. Noted in the link below.
https://documentation.onesignal.com/docs/cordova-sdk-setup#section-5-ios-part-2-recommend-

I wasn't able to reproduce this issue with a basic Cordova project. However I'll look into reproduce this issue with Ionic 3.4.0.

**Comment by luciandarabus** [comment]
@jkasten2 - I've re-started the project from scratch and the OneSignal plugin was working till I've added some ionic native components and plugins. I've redo this step by step using ionic cli 3.4.0 and report back if I still have the conflict and from where.

**Comment by Avislux** [comment]
Hey so any update on this? My app stops at a white screen after the splash on iOS, but on Android it works fine.

The errors won't appear when I first run the app, but they will if I refresh it. I also see the OneSignal.js in the sources.
I've tried `ionic cordova platform remove ios`, and `platform add ios`.
Then I went into the platforms/ios folder and ran `pod install`
I've done steps in Xcode where I enable push notifications and add OneSignal.framework to linked libraries. The app builds and runs fine but won't proceed after the splash.
I'm at a loss now.

**Comment by Avislux** [comment]
I finally solved it. The Safari console was telling me onesignal-cordova-plugin was not installed, but it was. The code initializing OneSignal has to go inside the this.platform.ready() promise. I had mine in the constructor. So something like this.
```
initializeApp() {
        this.platform.ready().then(() => {
            // Okay, so the platform is ready and our plugins are available.
            // Here you can do any higher level native things you might need.
            this.statusBar.styleDefault();
            this.splashScreen.hide();
            if (this.platform.is('cordova')) {
                /*Onesignal id and firebase id*/
                this.oneSignal.startInit('onesignal-id', 'google-id');
                this.oneSignal.inFocusDisplaying(this.oneSignal.OSInFocusDisplayOption.InAppAlert);
                this.oneSignal.handleNotificationReceived().subscribe((message) => {
                    // do something when notification is received
               
                });
                this.oneSignal.handleNotificationOpened().subscribe(() => {
                    // do something when a notification is opened
                });

                this.oneSignal.endInit();
            }
        });
    }
```

**Comment by hewham** [comment]
@Avislux 

Thank you for this it was driving me mad

**Comment by lilian131** [comment]
where is this initializeApp function please ?

**Comment by Avislux** [comment]
It's in app.component.ts .

**Comment by lilian131** [comment]
Thank you @Avislux I have got the same problem and my Code looks like the same 
```
platform.ready().then((res) => {
            
            if (res == 'cordova') {
                const googleKey = "googleKey ";
                const senderId = 'senderId';
                this.oneSignal.startInit(googleKey, senderId);
                this.oneSignal.inFocusDisplaying(this.oneSignal.OSInFocusDisplayOption.InAppAlert);
                this.oneSignal.handleNotificationReceived().subscribe(() => {
                });
                this.oneSignal.handleNotificationOpened().subscribe(() => {
                    console.log("notification opened!");
                });
                this.oneSignal.endInit();
            }
            statusBar.styleDefault();
            splashScreen.hide();

        });
```
