### ISSUE TITLE
Cannot build Cordova Android with latest 2.10.0 version

### ISSUE THREAD

**Issue by jasonandress** [OneSignal/OneSignal-Cordova-SDK#644]
**Description:**

Cannot build Cordova Android with latest 2.10.0 version

Get the following errors
/platforms/android/gradlew: Command failed with exit code 1 Error output:
platforms/android/app/src/main/java/com/plugin/gcm/OneSignalOutcomeController.java:25: error: unreported exception JSONException; must be caught or declared to be thrown
            CallbackHelper.callbackSuccess(jsSendUniqueOutcomeCallback, outcomeEvent.toJSONObject());
                                                                                                 ^
/platforms/android/app/src/main/java/com/plugin/gcm/OneSignalOutcomeController.java:45: error: unreported exception JSONException; must be caught or declared to be thrown
            CallbackHelper.callbackSuccess(jsSendOutcomeCallback, outcomeEvent.toJSONObject());
                                                                                           ^
/platforms/android/app/src/main/java/com/plugin/gcm/OneSignalOutcomeController.java:66: error: unreported exception JSONException; must be caught or declared to be thrown
            CallbackHelper.callbackSuccess(jsSendOutcomeWithValueCallback, outcomeEvent.toJSONObject()); 

**Environment**
1. What version of the Cordova SDK are you using? 2.10.0
2. Provide a list of your project dependencies (using `cordova plugin list` or copy-pasting your config.xml)

Ionic Info
Ionic:

   Ionic CLI         : 5.2.3 (/Users/jasonandress/.nvm/versions/node/v12.6.0/lib/node_modules/ionic)
   Ionic Framework   : ionic1 1.3.4
   @ionic/v1-toolkit : 2.0.6

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 6.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 23 other plugins)

Utility:

   cordova-res : 0.6.0 
   native-run  : 0.2.8 

System:

   Android SDK Tools : 26.1.1 (/Users//Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.2
   NodeJS            : v12.6.0 (/Users//.nvm/versions/node/v12.6.0/bin/node)
   npm               : 6.9.0
   OS                : macOS Catalina
   Xcode             : Xcode 11.5 Build version 11E608c

cordova-admob-plus 0.0.0 "@admob-plus/cordova"
cordova-annotated-plugin-android 1.0.4 "cordova-annotated-plugin-android"
cordova-plugin-add-swift-support 2.0.2 "AddSwiftSupport"
cordova-plugin-androidx 2.0.0 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.1 "cordova-plugin-androidx-adapter"
cordova-plugin-calendar 5.1.5 "Calendar"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 1.3.0 "Notification"
cordova-plugin-enable-multidex 0.2.0 "Enable Multidex"
cordova-plugin-facebook4 6.4.0 "Facebook Connect"
cordova-plugin-firebase-analytics 4.3.0 "FirebaseAnalyticsPlugin"
cordova-plugin-firebase-crash 2.2.0 "cordova-plugin-firebase-crash"
cordova-plugin-inappbrowser 4.0.0 "InAppBrowser"
cordova-plugin-intercom 8.0.0 "Intercom"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 5.0.0 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-purchases 1.1.0 "Purchases"
cordova-plugin-settings-hook 0.2.7 "Cordova Settings Hooks"
cordova-plugin-splashscreen 5.0.4 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-support-android-plugin 1.0.2 "cordova-support-android-plugin"
cordova-support-google-services 1.4.0 "cordova-support-google-services"
onesignal-cordova-plugin 2.9.1 "OneSignal Push Notifications"

**Steps to Reproduce Issue:**

1. Add 2.10.0 plugin version
2. Build android -- cordova run android
3. get errors above
4. Install 2.9.1 - compiles and runs with no errors

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by baroudihassan** [comment]
same error here

**Comment by tarun57** [comment]
Same error here

**Comment by bennol** [comment]
For everyone with this error that wants to go back to 2.9.1 until its fixed: 
`cordova plugin rm onesignal-cordova-plugin`
`cordova plugin add onesignal-cordova-plugin@2.9.1`

**Comment by indraraj26** [comment]
> Same error here and with 2.9.1 also in ionic 4 gives error on build.

use 2.8.4 it is working fine for me

**Comment by patrickbussmann** [comment]
Sometimes its funny - because the controller not changed since a half year.
*AND* 2.9.1 was released few months ago.
https://github.com/OneSignal/OneSignal-Cordova-SDK/blob/master/src/android/com/plugin/gcm/OneSignalOutcomeController.java

And with 2.9.1 it's working fine and with 2.10.0 not 😅

https://github.com/OneSignal/OneSignal-Cordova-SDK/commit/00246c301b6429e2ee74a2da922bc83abbc5ab54

So the only change is the OneSignal SDK from 3.13.2 to 3.14.1.

**Comment by ZumelzuR** [comment]
The problem is the oneSignal SDK, the problem should be there. Maybe they should first fix the error there (I think that is a missing dependency on the sdk maven definition)

then the version 2.10.0 should work

`    <framework src="com.onesignal:OneSignal:3.13.2" />
    <framework src="com.onesignal:OneSignal:3.14.1" />`

(I mean that first they should fix the 3.14.1 version of the android sdk)

**Comment by kakabreezy-prog** [comment]
Hi, everyone. Im so confused, im getting this error too. I was using OneSignal@2.7.0, i tried remove it and use version 2.10.0 and have the same error. I tried 2.9.1, 2.9.0, 2.8.4 and still getting the same error. I even remove onesignal-cordova-plugin from my project, but i still getting this error. I have been wondering why.. anyone can help me please? This is my final project. Thankyou very much, everyone

**Comment by patrickbussmann** [comment]
> Hi, everyone. Im so confused, im getting this error too. I was using OneSignal@2.7.0, i tried remove it and use version 2.10.0 and have the same error. I tried 2.9.1, 2.9.0, 2.8.4 and still getting the same error. I even remove onesignal-cordova-plugin from my project, but i still getting this error. I have been wondering why.. anyone can help me please? This is my final project. Thankyou very much, everyone

Did you clear your `platforms` and `plugins` folders?

**Comment by kakabreezy-prog** [comment]
> > Hi, everyone. Im so confused, im getting this error too. I was using OneSignal@2.7.0, i tried remove it and use version 2.10.0 and have the same error. I tried 2.9.1, 2.9.0, 2.8.4 and still getting the same error. I even remove onesignal-cordova-plugin from my project, but i still getting this error. I have been wondering why.. anyone can help me please? This is my final project. Thankyou very much, everyone
> 
> Did you clear your `platforms` and `plugins` folders?

I have just done it, there is no onesignal plugin already in plugins folder but there is still many in platforms, i just tried to delete it manually. im building my project..

**Comment by ZumelzuR** [comment]
> > > Hi, everyone. Im so confused, im getting this error too. I was using OneSignal@2.7.0, i tried remove it and use version 2.10.0 and have the same error. I tried 2.9.1, 2.9.0, 2.8.4 and still getting the same error. I even remove onesignal-cordova-plugin from my project, but i still getting this error. I have been wondering why.. anyone can help me please? This is my final project. Thankyou very much, everyone
> > 
> > 
> > Did you clear your `platforms` and `plugins` folders?
> 
> I have just done it, there is no onesignal plugin already in plugins folder but there is still many in platforms, i just tried to delete it manually. im building my project..

Remove the platforms and plugins folder, then change the plugin version of one signal and try to add the platform and build again.

Also take in note that you can have similar issues with other plugins (like google maps) so take a look to the path of the error. 

If you use 2.9.1 one signal you should not have this error. But you can have other errors related to Google play services dependencies that are quite similar.

**Comment by mikechoch** [comment]
Thank you for all of the information working on a fix for this now. Seems we reorganized some of our outcome event tracking and ended up moving the try-catch responsibility (for error logging) into a controller rather than the class itself now.

Be on the look out for a new release `2.10.0`
