### ISSUE TITLE
[Bug]: Our iOS builds have started to fail without any code changes `OneSignalExtension/OneSignalExtension.h' file not found`

### ISSUE THREAD

**Issue by kpturner** [OneSignal/OneSignal-Cordova-SDK#972]
### What happened?

Our overnight builds (that run on CircleCI) have started to fail, but we have not actually changed any code. 

### Steps to reproduce?

```Markdown
No steps to follow as such.  This is a standard project build.  It is as if something changed in the pod dependencies (which get installed/updated from scratch for a CI build).
```

### What did you expect to happen?

The build should not have started to just suddenly fail

### OneSignal Cordova SDK version

5.0.4

### Which platform(s) are affected?

- [X] iOS
- [ ] Android

### Relevant log output

```Shell
[13:49:54]: ▸ 2024-02-06 13:49:54.086 xcodebuild[8197:20655] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
[13:49:54]: ▸ Clean Succeeded
[13:49:58]: ▸ Copying Pods-OneSignalNotificationServiceExtension-umbrella.h
[13:49:58]: ▸ Processing Pods-OneSignalNotificationServiceExtension-Info.plist
[13:49:58]: ▸ Copying NSDictionary+CordovaPreferences.h
[13:49:58]: ▸ Copying CapacitorCordova.h
[13:49:58]: ▸ Copying CDVWebViewProcessPoolFactory.h
[13:49:58]: ▸ Copying CDVViewController.h
[13:49:58]: ▸ Copying CDVURLProtocol.h
[13:49:58]: ▸ Copying CDVScreenOrientationDelegate.h
[13:49:58]: ▸ Copying CDVPluginResult.h
[13:49:58]: ▸ Copying CDVPluginManager.h
[13:49:58]: ▸ Copying CDVPlugin.h
[13:49:58]: ▸ Copying CDVPlugin+Resources.h
[13:49:58]: ▸ Copying CDVInvokedUrlCommand.h
[13:49:58]: ▸ Copying CDVConfigParser.h
[13:49:58]: ▸ Copying CDVCommandDelegateImpl.h
[13:49:58]: ▸ Copying CDVCommandDelegate.h
[13:49:58]: ▸ Copying CDVAvailability.h
[13:49:58]: ▸ Copying CDV.h
[13:49:58]: ▸ Copying AppDelegate.h
[13:49:58]: ▸ Processing CapacitorCordova-Info.plist
[13:49:58]: ▸ Compiling NSDictionary+CordovaPreferences.m
[13:50:01]: ▸ Compiling Pods_OneSignalNotificationServiceExtension_vers.c
[13:50:01]: ▸ Compiling Pods-OneSignalNotificationServiceExtension-dummy.m
[13:50:01]: ▸ Compiling Cordova_vers.c
[13:50:01]: ▸ Compiling CapacitorCordova-dummy.m
[13:50:01]: ▸ Compiling CDVWebViewProcessPoolFactory.m
[13:50:01]: ▸ Compiling CDVViewController.m
[13:50:01]: ▸ Compiling CDVURLProtocol.m
[13:50:01]: ▸ Compiling CDVPluginResult.m
[13:50:01]: ▸ Compiling CDVPluginManager.m
[13:50:01]: ▸ Compiling CDVPlugin.m
[13:50:01]: ▸ Compiling CDVPlugin+Resources.m
[13:50:01]: ▸ Compiling CDVInvokedUrlCommand.m
[13:50:01]: ▸ Compiling CDVConfigParser.m
[13:50:01]: ▸ Compiling CDVCommandDelegateImpl.m
[13:50:01]: ▸ Compiling AppDelegate.m
[13:50:01]: ▸ Touching Pods_OneSignalNotificationServiceExtension.framework (in target 'Pods-OneSignalNotificationServiceExtension' from project 'Pods')
[13:50:01]: ▸ Processing Info.plist
[13:50:01]: ▸ Running script '[CP] Check Pods Manifest.lock'
[13:50:01]: ▸ Compiling NotificationService.m
[13:50:01]: ▸ ❌  /Users/distiller/project/packages/mobile/ios/App/OneSignalNotificationServiceExtension/NotificationService.m:1:9: 'OneSignalExtension/OneSignalExtension.h' file not found
[13:50:01]: ▸ #import <OneSignalExtension/OneSignalExtension.h>
[13:50:01]: ▸         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[13:50:02]: ▸ Linking Cordova
[13:50:02]: ▸ Generating 'Cordova.framework.dSYM'
[13:50:02]: ▸ Touching Cordova.framework (in target 'CapacitorCordova' from project 'Pods')
[13:50:02]: ▸ Copying OneSignalPush.h
[13:50:02]: ▸ Copying CordovaPluginsStatic-umbrella.h
[13:50:02]: ▸ Processing CordovaPluginsStatic-Info.plist
[13:50:02]: ▸ Compiling OneSignalPush.m
[13:50:02]: ▸ Compiling CordovaPluginsStatic-dummy.m
[13:50:02]: ▸ Compiling CordovaPluginsStatic_vers.c
[13:50:02]: ▸ Copying WKWebView+Capacitor.h
[13:50:02]: ▸ Copying Capacitor.h
[13:50:02]: ▸ Copying CAPPluginMethod.h
[13:50:02]: ▸ Copying CAPPluginCall.h
[13:50:02]: ▸ Copying CAPPlugin.h
[13:50:02]: ▸ Copying CAPInstanceDescriptor.h
[13:50:02]: ▸ Copying CAPInstanceConfiguration.h
[13:50:02]: ▸ Copying CAPBridgedPlugin.h
[13:50:02]: ▸ Copying CAPBridgedJSTypes.h
[13:50:02]: ▸ Copying CAPBridgeViewController+CDVScreenOrientationDelegate.h
[13:50:02]: ▸ Processing Capacitor-Info.plist
[13:50:02]: ▸ Copying /Users/distiller/Library/Developer/Xcode/DerivedData/App-euzjuftkxqdxmoeskgxmuwhvikiw/Build/Intermediates.noindex/ArchiveIntermediates/App/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Capacitor.framework/native-bridge.js
[13:50:02]: ▸     Run script build phase '[CP] Embed Pods Frameworks' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'App' from project 'App')
[13:50:02]: ▸ ** ARCHIVE FAILED **
[13:50:02]: ▸ The following build commands failed:
[13:50:02]: ▸   CompileC /Users/distiller/Library/Developer/Xcode/DerivedData/App-euzjuftkxqdxmoeskgxmuwhvikiw/Build/Intermediates.noindex/ArchiveIntermediates/App/IntermediateBuildFilesPath/App.build/Release-iphoneos/OneSignalNotificationServiceExtension.build/Objects-normal/arm64/NotificationService.o /Users/distiller/project/packages/mobile/ios/App/OneSignalNotificationServiceExtension/NotificationService.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'OneSignalNotificationServiceExtension' from project 'App')
[13:50:02]: ▸ (1 failure)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by apuchitnis** [comment]
We're also seeing the same issue.

**Comment by kpturner** [comment]
I don't know if it's relevant but the failed builds all seem to be using cocoapods 1.15.1

#If I force 1.15.2 it builds again ok 🤷‍♀️

**Comment by apuchitnis** [comment]
that works for us, thanks @kpturner!

**Comment by nan-li** [comment]
Thanks for reporting everyone, and that cocoapods update fixed it.

Very strange since it doesn't seem you made any changes to your OneSignal SDK dependency?

I see your post says you are on 5.0.4 @kpturner...Which day did your nightly builds start to fail? I wonder if your CI is actually pulling latest updates under the hood.

We released [Version 5.0.5](https://github.com/OneSignal/OneSignal-Cordova-SDK/releases/tag/5.0.5) on January 30.

**Comment by kpturner** [comment]
> We released [Version 5.0.5](https://github.com/OneSignal/OneSignal-Cordova-SDK/releases/tag/5.0.5) on January 30. Maybe it is doing this update automatically?

Thanks for the update.  We have been building every day since 30th without issue. It started failing on the 5th February I think - but it only failed in the CI (which is obviously a virgin install) but not locally.

I will check the logs to see if there are clues regarding the version of the SDK in use.

**Comment by kpturner** [comment]
I have checked the logs and the failures (using cocoapods 1.15.1) still show:
```
   onesignal-cordova-plugin@5.0.4
```

**Comment by kpturner** [comment]
This probably explains a lot
https://github.com/CocoaPods/CocoaPods/releases

**Comment by nan-li** [comment]
Ah, this makes sense. 

I'll close out this issue then!
